# Select image from https://hub.docker.com/_/php/
image: php:7.0

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git and unzip (composer will need them)
- apt-get update && apt-get install -qqy git unzip
# Install composer
- curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
# Create your .env file from the example file
- cp .env.testing .env
# Install all project dependencies
- composer install
# Create sqlite dbs
- touch storage/database.sqlitetouch storage/testing.sqlite
# Run migrations
- php artisan migrate && php artisan migrate --database=sqlite_testing
# Run webserver
- php -S localhost:8000 --docroot public &>/dev/null&

# Test
test:
  script:
  - vendor/bin/codecept build
  - vendor/bin/codecept run
